apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
  namespace: production
  labels:
    app: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: product-api
          image: onibokun/product-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-db-rw.database.svc.cluster.local
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: password
