apiVersion: v1
kind: Service
metadata:
  name: product-api-service
  namespace: production
  labels:
    app: product-service-api
spec:
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: product-api-web
