apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: onibokun/webapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: cluster-example-rw
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-example-app
                  key: password
