apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-2
  namespace: database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data # Shared storage path on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
                - node02
# Each postgres db instance has a separate copy of data.
# local-pv-2 is for the 2nd instance
