apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: postgres-db
  namespace: database
spec:
  instances: 3
  storage:
    size: 10Gi
    storageClass: local-storage
  monitoring:
    enablePodMonitor: true
