name: Build, Test, and Push Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        working-directory: ./Product.Catalog.Services/Product.Catalog.Products/ProductService
        run: dotnet restore

      - name: Build Product Service
        working-directory: ./Product.Catalog.Services/Product.Catalog.Products/ProductService
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests on Product Service
        working-directory: ./Product.Catalog.Services/Product.Catalog.Products/ProductService
        run: dotnet test --no-restore --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Product.Catalog.Services/Product.Catalog.Products/ProductService
          dockerfile: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webapi:latest
